################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
[en.params]
########### footer content ##########
footer_menu_left = "The group"
footer_menu_middle = "Products"
footer_menu_right = "Support"
footer_content = "The Glasgow Azure User Group is a community driven group based in Glasgow, Scotland. "


